In [10]:
import tensorflow as tf

tf.compat.v1.enable_eager_execution()


tf.executing_eagerly()


AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v1'

In [5]:
tf.print(ident)

<tf.Operation 'PrintV2' type=PrintV2>

In [6]:
init_op = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init_op) #execute init_op
    ident=tf.eye(3)
    #print the random values that we sample
    print (sess.run(ident))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [1]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  1
